Creature comforts and early exits.

diff --git a/trivy-diff b/trivy-diff
--- a/trivy-diff
+++ b/trivy-diff
@@ -2,7 +2,7 @@
 
 if ! command -v trivy &> /dev/null
 then
-    echo "Trivy must be installed for this command to work"
+    echo "trivy must be installed for this command to work"
     exit 1
 fi
 
@@ -12,8 +12,33 @@ then
     exit 2
 fi
 
+if ! docker image inspect $1 &> /dev/null
+then
+    echo "Could not find image $1"
+    exit 3
+fi
+
+if ! docker image inspect $2 &> /dev/null
+then
+    echo "Could not find image $2"
+    exit 4
+fi
+
 OLD_OUT=$(trivy -q i -f json $1 | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq)
+
+if ! $?
+then
+    echo "trivy only supports scanning on tag names - if the diff process failed, please try scanning against a tag"
+    exit 5
+fi
+
 NEW_OUT=$(trivy -q i -f json $2 | jq '.Results[]? | .Vulnerabilities[]? | .VulnerabilityID' | sort | uniq)
+
+if ! $?
+then
+    echo "trivy only supports scanning on tag names - if the diff process failed, please try scanning against a tag"
+    exit 6
+fi
 
 OLD_OUT=("${(@f)OLD_OUT}")
 NEW_OUT=("${(@f)NEW_OUT}")
